# Generated by Django 3.2.4 on 2021-06-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='bike',
        ),
        migrations.AddField(
            model_name='rental',
            name='bike',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bike', to='bikes.bike'),
        ),
    ]
