# Generated by Django 3.2.4 on 2021-06-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_auto_20210623_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='bike',
        ),
        migrations.AddField(
            model_name='rental',
            name='bike',
            field=models.ManyToManyField(related_name='bike', to='bikes.bike'),
        ),
    ]
