# Generated by Django 3.2.4 on 2021-07-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_auto_20210630_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='plan',
            field=models.TextField(default=''),
        ),
    ]
