# Generated by Django 3.2.4 on 2021-07-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_rental_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='bike',
            field=models.ManyToManyField(related_name='bike', to='bikes.Bike'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='bikes.rental')),
            ],
        ),
    ]
