# Generated by Django 3.2.4 on 2021-07-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_auto_20210702_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='bike',
            field=models.ManyToManyField(related_name='bike', to='bikes.Bike'),
        ),
    ]
